# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'DialogButtons.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_DialogButtonsCustomizationForm(object):
    def setupUi(self, DialogButtonsCustomizationForm):
        if not DialogButtonsCustomizationForm.objectName():
            DialogButtonsCustomizationForm.setObjectName(u"DialogButtonsCustomizationForm")
        DialogButtonsCustomizationForm.resize(374, 524)
        DialogButtonsCustomizationForm.setWindowTitle(u"Form")
#if QT_CONFIG(tooltip)
        DialogButtonsCustomizationForm.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        DialogButtonsCustomizationForm.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        DialogButtonsCustomizationForm.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        DialogButtonsCustomizationForm.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        DialogButtonsCustomizationForm.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        DialogButtonsCustomizationForm.setStyleSheet(u"background-color: rgba(255, 255, 255, 210);")
        self.groupBox = QGroupBox(DialogButtonsCustomizationForm)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 50, 351, 211))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 115, 151, 76))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.ok_width_spinBox = QSpinBox(self.groupBox_2)
        self.ok_width_spinBox.setObjectName(u"ok_width_spinBox")
        self.ok_width_spinBox.setGeometry(QRect(35, 30, 86, 27))
        self.ok_width_spinBox.setMinimum(20)
        self.ok_width_spinBox.setMaximum(99999)
        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(180, 115, 151, 76))
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.ok_height_spinBox = QSpinBox(self.groupBox_3)
        self.ok_height_spinBox.setObjectName(u"ok_height_spinBox")
        self.ok_height_spinBox.setGeometry(QRect(35, 30, 86, 27))
        self.ok_height_spinBox.setMinimum(20)
        self.ok_height_spinBox.setMaximum(99999)
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 30, 151, 76))
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.ok_x_spinBox = QSpinBox(self.groupBox_4)
        self.ok_x_spinBox.setObjectName(u"ok_x_spinBox")
        self.ok_x_spinBox.setGeometry(QRect(35, 30, 86, 27))
        self.ok_x_spinBox.setMinimum(5)
        self.ok_x_spinBox.setMaximum(99999)
        self.groupBox_5 = QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(180, 30, 151, 76))
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.ok_y_spinBox = QSpinBox(self.groupBox_5)
        self.ok_y_spinBox.setObjectName(u"ok_y_spinBox")
        self.ok_y_spinBox.setGeometry(QRect(35, 30, 86, 27))
        self.ok_y_spinBox.setMinimum(5)
        self.ok_y_spinBox.setMaximum(99999)
        self.groupBox_6 = QGroupBox(DialogButtonsCustomizationForm)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 265, 351, 211))
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.groupBox_7 = QGroupBox(self.groupBox_6)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(20, 115, 151, 76))
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.cancel_width_spinBox = QSpinBox(self.groupBox_7)
        self.cancel_width_spinBox.setObjectName(u"cancel_width_spinBox")
        self.cancel_width_spinBox.setGeometry(QRect(35, 30, 86, 27))
        self.cancel_width_spinBox.setMinimum(20)
        self.cancel_width_spinBox.setMaximum(99999)
        self.groupBox_8 = QGroupBox(self.groupBox_6)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(180, 115, 151, 76))
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.cancel_height_spinBox = QSpinBox(self.groupBox_8)
        self.cancel_height_spinBox.setObjectName(u"cancel_height_spinBox")
        self.cancel_height_spinBox.setGeometry(QRect(35, 30, 86, 27))
        self.cancel_height_spinBox.setMinimum(20)
        self.cancel_height_spinBox.setMaximum(99999)
        self.groupBox_9 = QGroupBox(self.groupBox_6)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(20, 30, 151, 76))
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.cancel_x_spinBox = QSpinBox(self.groupBox_9)
        self.cancel_x_spinBox.setObjectName(u"cancel_x_spinBox")
        self.cancel_x_spinBox.setGeometry(QRect(35, 30, 86, 27))
        self.cancel_x_spinBox.setMinimum(5)
        self.cancel_x_spinBox.setMaximum(99999)
        self.groupBox_10 = QGroupBox(self.groupBox_6)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(180, 30, 151, 76))
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.cancel_y_spinBox = QSpinBox(self.groupBox_10)
        self.cancel_y_spinBox.setObjectName(u"cancel_y_spinBox")
        self.cancel_y_spinBox.setGeometry(QRect(35, 30, 86, 27))
        self.cancel_y_spinBox.setMinimum(5)
        self.cancel_y_spinBox.setMaximum(99999)
        self.label = QLabel(DialogButtonsCustomizationForm)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(55, 5, 261, 36))
        self.label.setFont(font)
        self.label.setFrameShape(QFrame.StyledPanel)
        self.label.setFrameShadow(QFrame.Raised)
        self.label.setAlignment(Qt.AlignCenter)
        self.closeBtn = QPushButton(DialogButtonsCustomizationForm)
        self.closeBtn.setObjectName(u"closeBtn")
        self.closeBtn.setGeometry(QRect(85, 485, 93, 30))
        self.cancelBtn = QPushButton(DialogButtonsCustomizationForm)
        self.cancelBtn.setObjectName(u"cancelBtn")
        self.cancelBtn.setGeometry(QRect(190, 485, 93, 30))

        self.retranslateUi(DialogButtonsCustomizationForm)

        QMetaObject.connectSlotsByName(DialogButtonsCustomizationForm)
    # setupUi

    def retranslateUi(self, DialogButtonsCustomizationForm):
        self.groupBox.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"OK Button", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"Width", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"Height", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"X", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"Y", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"Cancel Button", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"Width", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"Height", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"X", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("DialogButtonsCustomizationForm", u"Y", None))
        self.label.setText(QCoreApplication.translate("DialogButtonsCustomizationForm", u"Dialog Buttons Customization", None))
        self.closeBtn.setText(QCoreApplication.translate("DialogButtonsCustomizationForm", u"OK", None))
        self.cancelBtn.setText(QCoreApplication.translate("DialogButtonsCustomizationForm", u"Cancel", None))
        pass
    # retranslateUi

