# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ImageImport.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_ImageImport(object):
    def setupUi(self, ImageImport):
        if not ImageImport.objectName():
            ImageImport.setObjectName(u"ImageImport")
        ImageImport.resize(797, 745)
        ImageImport.setModal(True)
        self.groupBox = QGroupBox(ImageImport)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(6, 10, 786, 261))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.importLogoBtn = QPushButton(self.groupBox)
        self.importLogoBtn.setObjectName(u"importLogoBtn")
        self.importLogoBtn.setGeometry(QRect(10, 80, 271, 32))
        self.importLogoBtn.setFont(font)
        self.importedLogoLabel = QLabel(self.groupBox)
        self.importedLogoLabel.setObjectName(u"importedLogoLabel")
        self.importedLogoLabel.setGeometry(QRect(314, 29, 151, 121))
        self.importedLogoLabel.setFrameShape(QFrame.StyledPanel)
        self.importedLogoLabel.setFrameShadow(QFrame.Raised)
        self.importedLogoLabel.setLineWidth(2)
        self.importedLogoLabel.setMidLineWidth(1)
        self.importedLogoLabel.setScaledContents(False)
        self.importedLogoLabel.setAlignment(Qt.AlignCenter)
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(399, 155, 91, 51))
        self.groupBox_4.setAlignment(Qt.AlignCenter)
        self.importedLogoHeightLabel = QLabel(self.groupBox_4)
        self.importedLogoHeightLabel.setObjectName(u"importedLogoHeightLabel")
        self.importedLogoHeightLabel.setGeometry(QRect(6, 25, 81, 19))
        self.importedLogoHeightLabel.setFrameShape(QFrame.NoFrame)
        self.importedLogoHeightLabel.setAlignment(Qt.AlignCenter)
        self.groupBox_5 = QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(295, 155, 91, 51))
        self.groupBox_5.setAlignment(Qt.AlignCenter)
        self.importedLogoWidthLabel = QLabel(self.groupBox_5)
        self.importedLogoWidthLabel.setObjectName(u"importedLogoWidthLabel")
        self.importedLogoWidthLabel.setGeometry(QRect(5, 25, 81, 19))
        self.importedLogoWidthLabel.setFrameShape(QFrame.NoFrame)
        self.importedLogoWidthLabel.setAlignment(Qt.AlignCenter)
        self.importedLogoFilenameLabel = QLabel(self.groupBox)
        self.importedLogoFilenameLabel.setObjectName(u"importedLogoFilenameLabel")
        self.importedLogoFilenameLabel.setGeometry(QRect(10, 225, 93, 29))
        self.importedLogoFilenameLabel.setMinimumSize(QSize(93, 29))
        self.importedLogoFilenameLabel.setMaximumSize(QSize(93, 29))
        self.importedLogoFilenameLabel.setFont(font)
        self.importedLogoFilenameLabel.setFrameShape(QFrame.StyledPanel)
        self.importedLogoFilenameLabel.setFrameShadow(QFrame.Raised)
        self.importedFilePath = QLabel(self.groupBox)
        self.importedFilePath.setObjectName(u"importedFilePath")
        self.importedFilePath.setGeometry(QRect(112, 225, 666, 29))
        self.importedFilePath.setMinimumSize(QSize(617, 29))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.importedFilePath.setFont(font1)
        self.importedFilePath.setFrameShape(QFrame.StyledPanel)
        self.importedFilePath.setFrameShadow(QFrame.Raised)
        self.importedFilePath.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.groupBox_2 = QGroupBox(ImageImport)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(5, 280, 786, 366))
        font2 = QFont()
        font2.setBold(True)
        font2.setWeight(75)
        self.groupBox_2.setFont(font2)
        self.imageStatusStackedWidget = QStackedWidget(self.groupBox_2)
        self.imageStatusStackedWidget.setObjectName(u"imageStatusStackedWidget")
        self.imageStatusStackedWidget.setGeometry(QRect(5, 25, 771, 331))
        self.BlankPage = QWidget()
        self.BlankPage.setObjectName(u"BlankPage")
        self.imageStatusStackedWidget.addWidget(self.BlankPage)
        self.ImageOK = QWidget()
        self.ImageOK.setObjectName(u"ImageOK")
        self.label = QLabel(self.ImageOK)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 45, 516, 106))
        self.saveImportedImageBtn = QPushButton(self.ImageOK)
        self.saveImportedImageBtn.setObjectName(u"saveImportedImageBtn")
        self.saveImportedImageBtn.setGeometry(QRect(15, 250, 271, 32))
        self.saveImportedImageBtn.setMinimumSize(QSize(177, 32))
        font3 = QFont()
        font3.setFamily(u"Arial")
        font3.setPointSize(14)
        font3.setBold(False)
        font3.setWeight(50)
        self.saveImportedImageBtn.setFont(font3)
        self.exportedFilePath = QLabel(self.ImageOK)
        self.exportedFilePath.setObjectName(u"exportedFilePath")
        self.exportedFilePath.setGeometry(QRect(105, 295, 666, 29))
        self.exportedFilePath.setMinimumSize(QSize(617, 29))
        self.exportedFilePath.setFont(font1)
        self.exportedFilePath.setFrameShape(QFrame.StyledPanel)
        self.exportedFilePath.setFrameShadow(QFrame.Raised)
        self.exportedFilePath.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.exportedLogoFilenameLabel = QLabel(self.ImageOK)
        self.exportedLogoFilenameLabel.setObjectName(u"exportedLogoFilenameLabel")
        self.exportedLogoFilenameLabel.setGeometry(QRect(3, 295, 93, 29))
        self.exportedLogoFilenameLabel.setMinimumSize(QSize(93, 29))
        self.exportedLogoFilenameLabel.setMaximumSize(QSize(93, 29))
        self.exportedLogoFilenameLabel.setFont(font3)
        self.exportedLogoFilenameLabel.setFrameShape(QFrame.StyledPanel)
        self.exportedLogoFilenameLabel.setFrameShadow(QFrame.Raised)
        self.imageStatusStackedWidget.addWidget(self.ImageOK)
        self.ImageWidthBad = QWidget()
        self.ImageWidthBad.setObjectName(u"ImageWidthBad")
        self.label_2 = QLabel(self.ImageWidthBad)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(25, 10, 736, 216))
        self.label_2.setWordWrap(True)
        self.increaseImageBtn = QPushButton(self.ImageWidthBad)
        self.increaseImageBtn.setObjectName(u"increaseImageBtn")
        self.increaseImageBtn.setGeometry(QRect(205, 225, 346, 32))
        self.increaseImageBtn.setMinimumSize(QSize(177, 32))
        self.increaseImageBtn.setFont(font3)
        self.decreaseImageBtn = QPushButton(self.ImageWidthBad)
        self.decreaseImageBtn.setObjectName(u"decreaseImageBtn")
        self.decreaseImageBtn.setGeometry(QRect(205, 295, 346, 32))
        self.decreaseImageBtn.setMinimumSize(QSize(177, 32))
        self.decreaseImageBtn.setFont(font3)
        self.label_3 = QLabel(self.ImageWidthBad)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(350, 263, 66, 26))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.imageStatusStackedWidget.addWidget(self.ImageWidthBad)
        self.switchToImportedLogoBtn = QPushButton(ImageImport)
        self.switchToImportedLogoBtn.setObjectName(u"switchToImportedLogoBtn")
        self.switchToImportedLogoBtn.setGeometry(QRect(30, 680, 281, 32))
        self.switchToImportedLogoBtn.setMinimumSize(QSize(177, 32))
        self.switchToImportedLogoBtn.setFont(font)
        self.closeImportWindowBtn = QPushButton(ImageImport)
        self.closeImportWindowBtn.setObjectName(u"closeImportWindowBtn")
        self.closeImportWindowBtn.setGeometry(QRect(485, 680, 281, 32))
        self.closeImportWindowBtn.setMinimumSize(QSize(177, 32))
        self.closeImportWindowBtn.setFont(font)

        self.retranslateUi(ImageImport)

        self.imageStatusStackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(ImageImport)
    # setupUi

    def retranslateUi(self, ImageImport):
        ImageImport.setWindowTitle(QCoreApplication.translate("ImageImport", u"Image Import", None))
        self.groupBox.setTitle(QCoreApplication.translate("ImageImport", u"Import Image", None))
#if QT_CONFIG(tooltip)
        self.importLogoBtn.setToolTip(QCoreApplication.translate("ImageImport", u"<html><head/><body><p>Currently, only BMP image format is supported when xrdp renders the logo. Use this facility to conveniently convert a JPG/PNG/GIF/etc image into it's corresponding BMP format.</p><p><br/></p><p>Note that any images which have an Alpha channel, will have that replaced with a white background.</p><p><br/></p><p>You should then save the converted file to a location convenient for xrdp to access.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.importLogoBtn.setText(QCoreApplication.translate("ImageImport", u"Select image file to import", None))
        self.importedLogoLabel.setText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("ImageImport", u"Height", None))
        self.importedLogoHeightLabel.setText(QCoreApplication.translate("ImageImport", u"0", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("ImageImport", u"Width", None))
        self.importedLogoWidthLabel.setText(QCoreApplication.translate("ImageImport", u"0", None))
        self.importedLogoFilenameLabel.setText(QCoreApplication.translate("ImageImport", u"Filename", None))
        self.importedFilePath.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("ImageImport", u"Image Status", None))
        self.label.setText(QCoreApplication.translate("ImageImport", u"<html><head/><body><p><span style=\" font-weight:600; color:#008000;\">Image is OK.</span></p><p>You can now save the image and use it as a</p><p>BMP file for use as the XRDP login window logo.</p></body></html>", None))
        self.saveImportedImageBtn.setText(QCoreApplication.translate("ImageImport", u"Save Imported Image as BMP", None))
        self.exportedFilePath.setText("")
        self.exportedLogoFilenameLabel.setText(QCoreApplication.translate("ImageImport", u"Filename", None))
        self.label_2.setText(QCoreApplication.translate("ImageImport", u"<html><head/><body><p><span style=\" font-weight:600; color:#c00000;\">Image has a problem.</span></p><p>Currently, XRDP has a bug whereby if the image Width is not divisible by 4, the image will not be displayed properly in the xrdp login window.</p><p><br/>XRDPConfigurator can rescale the image for you, just one of click the buttons below and the image will be rescaled up or down to the closest width value divisible by 4.</p><p>The aspect ratio of the image will be kept.</p></body></html>", None))
        self.increaseImageBtn.setText(QCoreApplication.translate("ImageImport", u"Increase image width by pixels", None))
        self.decreaseImageBtn.setText(QCoreApplication.translate("ImageImport", u"Decrease image width by pixels", None))
        self.label_3.setText(QCoreApplication.translate("ImageImport", u"or", None))
        self.switchToImportedLogoBtn.setText(QCoreApplication.translate("ImageImport", u"Use image as Logo and close", None))
        self.closeImportWindowBtn.setText(QCoreApplication.translate("ImageImport", u"Close import window", None))
    # retranslateUi

