# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'labelsAndBoxes.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_labelsAndBoxes(object):
    def setupUi(self, labelsAndBoxes):
        if not labelsAndBoxes.objectName():
            labelsAndBoxes.setObjectName(u"labelsAndBoxes")
        labelsAndBoxes.resize(374, 524)
        labelsAndBoxes.setWindowTitle(u"Labels and Boxes")
#if QT_CONFIG(tooltip)
        labelsAndBoxes.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        labelsAndBoxes.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(accessibility)
        labelsAndBoxes.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        labelsAndBoxes.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        labelsAndBoxes.setStyleSheet(u"background-color: rgba(255, 255, 255, 210);")
        self.okBtn = QPushButton(labelsAndBoxes)
        self.okBtn.setObjectName(u"okBtn")
        self.okBtn.setGeometry(QRect(75, 485, 93, 30))
        self.cancelBtn = QPushButton(labelsAndBoxes)
        self.cancelBtn.setObjectName(u"cancelBtn")
        self.cancelBtn.setGeometry(QRect(195, 485, 93, 30))
        self.groupBox = QGroupBox(labelsAndBoxes)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 50, 356, 211))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(14)
        self.groupBox.setFont(font)
#if QT_CONFIG(statustip)
        self.groupBox.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.groupBox.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.groupBox.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.groupBox.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.groupBox.setTitle(u"Labels")
        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(100, 70, 151, 76))
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.labels_x_spinbox = QSpinBox(self.groupBox_3)
        self.labels_x_spinbox.setObjectName(u"labels_x_spinbox")
        self.labels_x_spinbox.setGeometry(QRect(30, 30, 86, 27))
        font1 = QFont()
        font1.setBold(False)
        font1.setWeight(50)
        self.labels_x_spinbox.setFont(font1)
        self.labels_x_spinbox.setReadOnly(True)
        self.labels_x_spinbox.setMinimum(5)
        self.labels_x_spinbox.setMaximum(999999999)
        self.groupBox_2 = QGroupBox(labelsAndBoxes)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 265, 356, 211))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setPointSize(14)
        font2.setBold(False)
        font2.setWeight(50)
        self.groupBox_2.setFont(font2)
        self.groupBox_2.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.groupBox_4 = QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 20, 151, 76))
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.boxes_x_spinbox = QSpinBox(self.groupBox_4)
        self.boxes_x_spinbox.setObjectName(u"boxes_x_spinbox")
        self.boxes_x_spinbox.setGeometry(QRect(35, 30, 86, 27))
        self.boxes_x_spinbox.setReadOnly(True)
        self.boxes_x_spinbox.setMaximum(999999999)
        self.groupBox_5 = QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(185, 20, 151, 76))
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.boxes_y_spinbox = QSpinBox(self.groupBox_5)
        self.boxes_y_spinbox.setObjectName(u"boxes_y_spinbox")
        self.boxes_y_spinbox.setGeometry(QRect(35, 30, 86, 27))
        self.boxes_y_spinbox.setReadOnly(True)
        self.boxes_y_spinbox.setMaximum(999999999)
        self.groupBox_6 = QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(105, 100, 151, 76))
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.boxes_w_spinbox = QSpinBox(self.groupBox_6)
        self.boxes_w_spinbox.setObjectName(u"boxes_w_spinbox")
        self.boxes_w_spinbox.setGeometry(QRect(35, 30, 86, 27))
        self.boxes_w_spinbox.setReadOnly(True)
        self.boxes_w_spinbox.setMaximum(999999999)
        self.label = QLabel(labelsAndBoxes)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(45, 5, 281, 36))
        self.label.setFont(font)
        self.label.setFrameShape(QFrame.StyledPanel)
        self.label.setFrameShadow(QFrame.Raised)
        self.label.setAlignment(Qt.AlignCenter)

        self.retranslateUi(labelsAndBoxes)

        QMetaObject.connectSlotsByName(labelsAndBoxes)
    # setupUi

    def retranslateUi(self, labelsAndBoxes):
        self.okBtn.setText(QCoreApplication.translate("labelsAndBoxes", u"OK", None))
        self.cancelBtn.setText(QCoreApplication.translate("labelsAndBoxes", u"Cancel", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("labelsAndBoxes", u"X", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("labelsAndBoxes", u"Boxes", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("labelsAndBoxes", u"X", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("labelsAndBoxes", u"Y", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("labelsAndBoxes", u"Width", None))
        self.label.setText(QCoreApplication.translate("labelsAndBoxes", u"Labels & Boxes Customization", None))
        pass
    # retranslateUi

