# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'LogoCustomization.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_LogoCustomization(object):
    def setupUi(self, LogoCustomization):
        if not LogoCustomization.objectName():
            LogoCustomization.setObjectName(u"LogoCustomization")
        LogoCustomization.resize(797, 745)
        LogoCustomization.setMinimumSize(QSize(797, 745))
        LogoCustomization.setMaximumSize(QSize(797, 745))
        LogoCustomization.setSizeGripEnabled(False)
        LogoCustomization.setModal(False)
        self.currentLogoGroupBox = QGroupBox(LogoCustomization)
        self.currentLogoGroupBox.setObjectName(u"currentLogoGroupBox")
        self.currentLogoGroupBox.setGeometry(QRect(10, 6, 777, 291))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(14)
        self.currentLogoGroupBox.setFont(font)
        self.logoFilePath = QLabel(self.currentLogoGroupBox)
        self.logoFilePath.setObjectName(u"logoFilePath")
        self.logoFilePath.setGeometry(QRect(114, 255, 657, 29))
        self.logoFilePath.setMinimumSize(QSize(617, 29))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.logoFilePath.setFont(font1)
        self.logoFilePath.setFrameShape(QFrame.StyledPanel)
        self.logoFilePath.setFrameShadow(QFrame.Raised)
        self.logoFilePath.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.currentLogoFilenameLabel = QLabel(self.currentLogoGroupBox)
        self.currentLogoFilenameLabel.setObjectName(u"currentLogoFilenameLabel")
        self.currentLogoFilenameLabel.setGeometry(QRect(12, 255, 93, 29))
        self.currentLogoFilenameLabel.setMinimumSize(QSize(93, 29))
        self.currentLogoFilenameLabel.setMaximumSize(QSize(93, 29))
        self.currentLogoFilenameLabel.setFont(font)
        self.currentLogoFilenameLabel.setFrameShape(QFrame.StyledPanel)
        self.currentLogoFilenameLabel.setFrameShadow(QFrame.Raised)
        self.currentLogoLabel = QLabel(self.currentLogoGroupBox)
        self.currentLogoLabel.setObjectName(u"currentLogoLabel")
        self.currentLogoLabel.setGeometry(QRect(315, 60, 151, 121))
        self.currentLogoLabel.setFrameShape(QFrame.StyledPanel)
        self.currentLogoLabel.setFrameShadow(QFrame.Raised)
        self.currentLogoLabel.setLineWidth(2)
        self.currentLogoLabel.setMidLineWidth(1)
        self.currentLogoLabel.setScaledContents(False)
        self.currentLogoLabel.setAlignment(Qt.AlignCenter)
        self.groupBox_2 = QGroupBox(self.currentLogoGroupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(290, 185, 96, 56))
        self.currentLogoWidthLabel = QLabel(self.groupBox_2)
        self.currentLogoWidthLabel.setObjectName(u"currentLogoWidthLabel")
        self.currentLogoWidthLabel.setGeometry(QRect(10, 25, 77, 19))
        self.currentLogoWidthLabel.setAlignment(Qt.AlignCenter)
        self.groupBox_3 = QGroupBox(self.currentLogoGroupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(395, 185, 96, 56))
        self.currentLogoHeightLabel = QLabel(self.groupBox_3)
        self.currentLogoHeightLabel.setObjectName(u"currentLogoHeightLabel")
        self.currentLogoHeightLabel.setGeometry(QRect(10, 25, 77, 19))
        self.currentLogoHeightLabel.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.currentLogoGroupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(210, 40, 361, 16))
        self.label.setAlignment(Qt.AlignCenter)
        self.closeButton = QPushButton(LogoCustomization)
        self.closeButton.setObjectName(u"closeButton")
        self.closeButton.setGeometry(QRect(705, 700, 80, 30))
        self.changeLogoBtn = QPushButton(LogoCustomization)
        self.changeLogoBtn.setObjectName(u"changeLogoBtn")
        self.changeLogoBtn.setGeometry(QRect(5, 655, 391, 32))
        self.changeLogoBtn.setMinimumSize(QSize(149, 32))
        self.changeLogoBtn.setFont(font)
        self.importAnImageBtn = QPushButton(LogoCustomization)
        self.importAnImageBtn.setObjectName(u"importAnImageBtn")
        self.importAnImageBtn.setGeometry(QRect(400, 655, 391, 32))
        self.importAnImageBtn.setMinimumSize(QSize(149, 32))
        self.importAnImageBtn.setFont(font)
        self.imageStatusGroupBox = QGroupBox(LogoCustomization)
        self.imageStatusGroupBox.setObjectName(u"imageStatusGroupBox")
        self.imageStatusGroupBox.setGeometry(QRect(10, 305, 776, 341))
        font2 = QFont()
        font2.setBold(True)
        font2.setWeight(75)
        self.imageStatusGroupBox.setFont(font2)
        self.imageStatusStackedWidget = QStackedWidget(self.imageStatusGroupBox)
        self.imageStatusStackedWidget.setObjectName(u"imageStatusStackedWidget")
        self.imageStatusStackedWidget.setGeometry(QRect(5, 25, 761, 241))
        font3 = QFont()
        font3.setPointSize(13)
        font3.setBold(False)
        font3.setWeight(50)
        self.imageStatusStackedWidget.setFont(font3)
        self.BlankPage = QWidget()
        self.BlankPage.setObjectName(u"BlankPage")
        self.imageStatusStackedWidget.addWidget(self.BlankPage)
        self.ImageOK = QWidget()
        self.ImageOK.setObjectName(u"ImageOK")
        self.label_2 = QLabel(self.ImageOK)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 45, 726, 106))
        font4 = QFont()
        font4.setPointSize(14)
        self.label_2.setFont(font4)
        self.label_2.setWordWrap(True)
        self.imageStatusStackedWidget.addWidget(self.ImageOK)
        self.ImageWidthBad = QWidget()
        self.ImageWidthBad.setObjectName(u"ImageWidthBad")
        self.label_3 = QLabel(self.ImageWidthBad)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(25, 10, 736, 251))
        self.label_3.setWordWrap(True)
        self.imageStatusStackedWidget.addWidget(self.ImageWidthBad)

        self.retranslateUi(LogoCustomization)

        self.imageStatusStackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(LogoCustomization)
    # setupUi

    def retranslateUi(self, LogoCustomization):
        LogoCustomization.setWindowTitle(QCoreApplication.translate("LogoCustomization", u"Logo Customization", None))
        self.currentLogoGroupBox.setTitle(QCoreApplication.translate("LogoCustomization", u"Current Logo", None))
        self.logoFilePath.setText(QCoreApplication.translate("LogoCustomization", u"TextLabel", None))
        self.currentLogoFilenameLabel.setText(QCoreApplication.translate("LogoCustomization", u"Filename", None))
        self.currentLogoLabel.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("LogoCustomization", u"Width", None))
        self.currentLogoWidthLabel.setText(QCoreApplication.translate("LogoCustomization", u"0", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("LogoCustomization", u"Height", None))
        self.currentLogoHeightLabel.setText(QCoreApplication.translate("LogoCustomization", u"0", None))
        self.label.setText(QCoreApplication.translate("LogoCustomization", u"(Scaled - mouseover to see full size)", None))
        self.closeButton.setText(QCoreApplication.translate("LogoCustomization", u"Close", None))
#if QT_CONFIG(tooltip)
        self.changeLogoBtn.setToolTip(QCoreApplication.translate("LogoCustomization", u"<html><head/><body><p>Select a BMP-format image to be used as the xrdp logo. The INI file will be updated with the full pathname of this image file.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.changeLogoBtn.setText(QCoreApplication.translate("LogoCustomization", u"Select a new existing Logo File (BMP format)", None))
#if QT_CONFIG(tooltip)
        self.importAnImageBtn.setToolTip(QCoreApplication.translate("LogoCustomization", u"<html><head/><body><p>Select a BMP-format image to be used as the xrdp logo. The INI file will be updated with the full pathname of this image file.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.importAnImageBtn.setText(QCoreApplication.translate("LogoCustomization", u"Import and convert an image to BMP format", None))
        self.imageStatusGroupBox.setTitle(QCoreApplication.translate("LogoCustomization", u"Image Status", None))
        self.label_2.setText(QCoreApplication.translate("LogoCustomization", u"<html><head/><body><p><span style=\" font-weight:600; color:#008000;\">Image is OK.</span></p><p>The width of the currently used image is divisible by 4 and will be properly displayed by xrdp.</p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("LogoCustomization", u"<html><head/><body><p><span style=\" font-weight:600; color:#c00000;\">The currently used image has a problem.</span></p><p>XRDP versions 0.8 and below (and possibly current) have a bug whereby if the image width is not divisible by 4, the image will not be displayed properly in the xrdp login window.</p><p><br/>XRDPConfigurator can rescale the image for you; just use the &quot;<span style=\" font-weight:600;\">Import and convert an image to BMP format</span>&quot; button, then import that image, rescale it, and save it again.</p><p>Alternatively, select a pre-existing BMP image which<br/>has a width divisble by 4.</p></body></html>", None))
    # retranslateUi

