# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SessionFrame.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_sessionConfigForm(object):
    def setupUi(self, sessionConfigForm):
        if not sessionConfigForm.objectName():
            sessionConfigForm.setObjectName(u"sessionConfigForm")
        sessionConfigForm.resize(1056, 512)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sessionConfigForm.sizePolicy().hasHeightForWidth())
        sessionConfigForm.setSizePolicy(sizePolicy)
        sessionConfigForm.setLayoutDirection(Qt.LeftToRight)
        sessionConfigForm.setInputMethodHints(Qt.ImhNone)
        self.label_2 = QLabel(sessionConfigForm)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 128, 139, 35))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QFrame.StyledPanel)
        self.label_2.setFrameShadow(QFrame.Raised)
        self.label_2.setTextFormat(Qt.PlainText)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.libraryComboBox = QComboBox(sessionConfigForm)
        self.libraryComboBox.addItem("")
        self.libraryComboBox.addItem("")
        self.libraryComboBox.addItem("")
        self.libraryComboBox.addItem("")
        self.libraryComboBox.addItem("")
        self.libraryComboBox.setObjectName(u"libraryComboBox")
        self.libraryComboBox.setGeometry(QRect(184, 128, 265, 35))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(12)
        font1.setBold(False)
        font1.setWeight(50)
        self.libraryComboBox.setFont(font1)
        self.sessionIPAddress = QLineEdit(sessionConfigForm)
        self.sessionIPAddress.setObjectName(u"sessionIPAddress")
        self.sessionIPAddress.setGeometry(QRect(184, 226, 266, 36))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setPointSize(16)
        self.sessionIPAddress.setFont(font2)
        self.sessionIPAddress.setInputMask(u"")
        self.sessionIPAddress.setFrame(True)
        self.sessionIPAddress.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(sessionConfigForm)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(29, 226, 141, 36))
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_3.setFrameShape(QFrame.StyledPanel)
        self.label_3.setFrameShadow(QFrame.Raised)
        self.label_3.setTextFormat(Qt.PlainText)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setTextInteractionFlags(Qt.NoTextInteraction)
        self.sessionPortEntryBox = QLineEdit(sessionConfigForm)
        self.sessionPortEntryBox.setObjectName(u"sessionPortEntryBox")
        self.sessionPortEntryBox.setGeometry(QRect(184, 271, 266, 36))
        self.sessionPortEntryBox.setFont(font2)
        self.sessionPortEntryBox.setAlignment(Qt.AlignCenter)
        self.sessionport_label = QLabel(sessionConfigForm)
        self.sessionport_label.setObjectName(u"sessionport_label")
        self.sessionport_label.setGeometry(QRect(29, 271, 141, 36))
        self.sessionport_label.setFont(font)
        self.sessionport_label.setLayoutDirection(Qt.LeftToRight)
        self.sessionport_label.setAutoFillBackground(False)
        self.sessionport_label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.sessionport_label.setFrameShape(QFrame.StyledPanel)
        self.sessionport_label.setFrameShadow(QFrame.Raised)
        self.sessionport_label.setTextFormat(Qt.RichText)
        self.sessionport_label.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(sessionConfigForm)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(31, 406, 139, 36))
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_8.setFrameShape(QFrame.StyledPanel)
        self.label_8.setFrameShadow(QFrame.Raised)
        self.label_8.setTextFormat(Qt.RichText)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.sessionPasswordEntryBox = QLineEdit(sessionConfigForm)
        self.sessionPasswordEntryBox.setObjectName(u"sessionPasswordEntryBox")
        self.sessionPasswordEntryBox.setGeometry(QRect(184, 406, 266, 36))
        self.sessionPasswordEntryBox.setFont(font2)
        self.sessionPasswordEntryBox.setEchoMode(QLineEdit.Normal)
        self.sessionPasswordEntryBox.setAlignment(Qt.AlignCenter)
        self.sessionUserNameEntryBox = QLineEdit(sessionConfigForm)
        self.sessionUserNameEntryBox.setObjectName(u"sessionUserNameEntryBox")
        self.sessionUserNameEntryBox.setGeometry(QRect(184, 361, 266, 36))
        self.sessionUserNameEntryBox.setFont(font2)
        self.sessionUserNameEntryBox.setInputMask(u"")
        self.sessionUserNameEntryBox.setFrame(True)
        self.sessionUserNameEntryBox.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(sessionConfigForm)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 360, 139, 36))
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QFrame.StyledPanel)
        self.label_4.setFrameShadow(QFrame.Raised)
        self.label_4.setTextFormat(Qt.RichText)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(sessionConfigForm)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(345, 10, 386, 91))
        font3 = QFont()
        font3.setPointSize(15)
        self.label_5.setFont(font3)
        self.label_5.setFrameShape(QFrame.StyledPanel)
        self.label_5.setFrameShadow(QFrame.Raised)
        self.label_5.setTextFormat(Qt.AutoText)
        self.label_5.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.sessionNameBox = QLineEdit(sessionConfigForm)
        self.sessionNameBox.setObjectName(u"sessionNameBox")
        self.sessionNameBox.setGeometry(QRect(355, 50, 366, 41))
        self.sessionNameBox.setFont(font2)
        self.sessionNameBox.setFrame(True)
        self.sessionNameBox.setAlignment(Qt.AlignCenter)
        self.chansrvport_label = QLabel(sessionConfigForm)
        self.chansrvport_label.setObjectName(u"chansrvport_label")
        self.chansrvport_label.setEnabled(False)
        self.chansrvport_label.setGeometry(QRect(29, 316, 141, 35))
        self.chansrvport_label.setFont(font)
        self.chansrvport_label.setLayoutDirection(Qt.LeftToRight)
        self.chansrvport_label.setAutoFillBackground(False)
        self.chansrvport_label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.chansrvport_label.setFrameShape(QFrame.StyledPanel)
        self.chansrvport_label.setFrameShadow(QFrame.Raised)
        self.chansrvport_label.setTextFormat(Qt.RichText)
        self.chansrvport_label.setAlignment(Qt.AlignCenter)
        self.chansrvPortEntryBox = QLineEdit(sessionConfigForm)
        self.chansrvPortEntryBox.setObjectName(u"chansrvPortEntryBox")
        self.chansrvPortEntryBox.setEnabled(False)
        self.chansrvPortEntryBox.setGeometry(QRect(184, 316, 266, 36))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.chansrvPortEntryBox.setFont(font4)
        self.chansrvPortEntryBox.setAlignment(Qt.AlignCenter)
        self.chansrvPortEntryBox.setReadOnly(True)
        self.channelsFrame = QFrame(sessionConfigForm)
        self.channelsFrame.setObjectName(u"channelsFrame")
        self.channelsFrame.setEnabled(False)
        self.channelsFrame.setGeometry(QRect(509, 126, 516, 316))
        self.channelsFrame.setAutoFillBackground(False)
        self.channelsFrame.setFrameShape(QFrame.StyledPanel)
        self.channelsFrame.setFrameShadow(QFrame.Raised)
        self.label_13 = QLabel(self.channelsFrame)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(140, 19, 236, 36))
        font5 = QFont()
        font5.setBold(False)
        font5.setWeight(50)
        self.label_13.setFont(font5)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setFrameShape(QFrame.StyledPanel)
        self.label_13.setFrameShadow(QFrame.Raised)
        self.label_13.setLineWidth(2)
        self.label_13.setMidLineWidth(1)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.useXrdpVrCheckBox = QCheckBox(self.channelsFrame)
        self.useXrdpVrCheckBox.setObjectName(u"useXrdpVrCheckBox")
        self.useXrdpVrCheckBox.setGeometry(QRect(15, 254, 496, 21))
        font6 = QFont()
        font6.setFamily(u"Arial")
        font6.setPointSize(11)
        font6.setBold(True)
        font6.setWeight(75)
        self.useXrdpVrCheckBox.setFont(font6)
        self.useXrdpVrCheckBox.setLayoutDirection(Qt.LeftToRight)
        self.useClipRdrCheckBox = QCheckBox(self.channelsFrame)
        self.useClipRdrCheckBox.setObjectName(u"useClipRdrCheckBox")
        self.useClipRdrCheckBox.setGeometry(QRect(15, 194, 496, 21))
        self.useClipRdrCheckBox.setFont(font6)
        self.useClipRdrCheckBox.setLayoutDirection(Qt.LeftToRight)
        self.useRAILCheckBox = QCheckBox(self.channelsFrame)
        self.useRAILCheckBox.setObjectName(u"useRAILCheckBox")
        self.useRAILCheckBox.setGeometry(QRect(15, 224, 496, 21))
        self.useRAILCheckBox.setFont(font6)
        self.useRAILCheckBox.setLayoutDirection(Qt.LeftToRight)
        self.useRdpSndCheckBox = QCheckBox(self.channelsFrame)
        self.useRdpSndCheckBox.setObjectName(u"useRdpSndCheckBox")
        self.useRdpSndCheckBox.setGeometry(QRect(15, 134, 496, 21))
        self.useRdpSndCheckBox.setFont(font6)
        self.useRdpSndCheckBox.setLayoutDirection(Qt.LeftToRight)
        self.useDrDynVcCheckBox = QCheckBox(self.channelsFrame)
        self.useDrDynVcCheckBox.setObjectName(u"useDrDynVcCheckBox")
        self.useDrDynVcCheckBox.setGeometry(QRect(15, 164, 496, 21))
        self.useDrDynVcCheckBox.setFont(font6)
        self.useDrDynVcCheckBox.setLayoutDirection(Qt.LeftToRight)
        self.useRdpDrCheckBox = QCheckBox(self.channelsFrame)
        self.useRdpDrCheckBox.setObjectName(u"useRdpDrCheckBox")
        self.useRdpDrCheckBox.setGeometry(QRect(15, 104, 496, 21))
        self.useRdpDrCheckBox.setFont(font6)
        self.useRdpDrCheckBox.setLayoutDirection(Qt.LeftToRight)
        self.enableOverridesCheckBox = QCheckBox(sessionConfigForm)
        self.enableOverridesCheckBox.setObjectName(u"enableOverridesCheckBox")
        self.enableOverridesCheckBox.setGeometry(QRect(510, 456, 226, 21))
        self.enableOverridesCheckBox.setLayoutDirection(Qt.LeftToRight)
        self.sessionSectionName = QLabel(sessionConfigForm)
        self.sessionSectionName.setObjectName(u"sessionSectionName")
        self.sessionSectionName.setGeometry(QRect(945, 5, 106, 36))
        font7 = QFont()
        font7.setPointSize(15)
        font7.setBold(True)
        font7.setItalic(False)
        font7.setWeight(75)
        self.sessionSectionName.setFont(font7)
        self.sessionSectionName.setFrameShape(QFrame.StyledPanel)
        self.sessionSectionName.setFrameShadow(QFrame.Raised)
        self.sessionSectionName.setTextFormat(Qt.PlainText)
        self.sessionSectionName.setAlignment(Qt.AlignCenter)
        self.debugXRDPCheckbox = QCheckBox(sessionConfigForm)
        self.debugXRDPCheckbox.setObjectName(u"debugXRDPCheckbox")
        self.debugXRDPCheckbox.setEnabled(True)
        self.debugXRDPCheckbox.setGeometry(QRect(925, 45, 126, 21))
        font8 = QFont()
        font8.setPointSize(11)
        font8.setBold(False)
        font8.setWeight(50)
        self.debugXRDPCheckbox.setFont(font8)
        self.debugXRDPCheckbox.setLayoutDirection(Qt.RightToLeft)
        self.debugXRDPCheckbox.setChecked(False)
        self.serverbpplabel = QLabel(sessionConfigForm)
        self.serverbpplabel.setObjectName(u"serverbpplabel")
        self.serverbpplabel.setGeometry(QRect(30, 174, 139, 35))
        self.serverbpplabel.setFont(font)
        self.serverbpplabel.setAutoFillBackground(False)
        self.serverbpplabel.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.serverbpplabel.setFrameShape(QFrame.StyledPanel)
        self.serverbpplabel.setFrameShadow(QFrame.Raised)
        self.serverbpplabel.setTextFormat(Qt.PlainText)
        self.serverbpplabel.setAlignment(Qt.AlignCenter)
        self.serverbppcombobox = QComboBox(sessionConfigForm)
        self.serverbppcombobox.addItem("")
        self.serverbppcombobox.addItem("")
        self.serverbppcombobox.addItem("")
        self.serverbppcombobox.addItem("")
        self.serverbppcombobox.addItem("")
        self.serverbppcombobox.setObjectName(u"serverbppcombobox")
        self.serverbppcombobox.setGeometry(QRect(184, 174, 265, 35))
        self.serverbppcombobox.setFont(font1)

        self.retranslateUi(sessionConfigForm)

        QMetaObject.connectSlotsByName(sessionConfigForm)
    # setupUi

    def retranslateUi(self, sessionConfigForm):
        sessionConfigForm.setWindowTitle(QCoreApplication.translate("sessionConfigForm", u"Form", None))
#if QT_CONFIG(tooltip)
        sessionConfigForm.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("sessionConfigForm", u"Connection Type", None))
        self.libraryComboBox.setItemText(0, QCoreApplication.translate("sessionConfigForm", u"x11rdp back-end (libxup.so)", None))
        self.libraryComboBox.setItemText(1, QCoreApplication.translate("sessionConfigForm", u"Xvnc back-end (libvnc.so)", None))
        self.libraryComboBox.setItemText(2, QCoreApplication.translate("sessionConfigForm", u"RDP \"Any\" (librdp.so)", None))
        self.libraryComboBox.setItemText(3, QCoreApplication.translate("sessionConfigForm", u"FreeRDP back-end (libxrdpfreerdp1.so)", None))
        self.libraryComboBox.setItemText(4, QCoreApplication.translate("sessionConfigForm", u"Neutrinolabs back-end (libxrdpneutrinordp.so)", None))

#if QT_CONFIG(tooltip)
        self.libraryComboBox.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>Define the connection type here, which in turn defines what back-end will be used to display your session.</p><p>e.g. Xrdp or Xvnc back-end.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.sessionIPAddress.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>This specifies the IP address of the <span style=\" font-weight:600;\">host</span> to connect to.</p><p>If the Xrdp host runs on the same system, then this is set to <span style=\" font-weight:600;\">127.0.0.1</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.sessionIPAddress.setText("")
        self.label_3.setText(QCoreApplication.translate("sessionConfigForm", u"IP Address", None))
#if QT_CONFIG(tooltip)
        self.sessionPortEntryBox.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>Specifies the port number to connect to.</p><p>If this is set to <span style=\" font-weight:600;\">-1</span>, then the default port for the specified library is used.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.sessionPortEntryBox.setText(QCoreApplication.translate("sessionConfigForm", u"3389", None))
        self.sessionport_label.setText(QCoreApplication.translate("sessionConfigForm", u"Port", None))
        self.label_8.setText(QCoreApplication.translate("sessionConfigForm", u"Password", None))
#if QT_CONFIG(tooltip)
        self.sessionPasswordEntryBox.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>Specifies the password used for RDP authentication.</p><p>When set to <span style=\" font-weight:600;\">ask</span>, the user needs to input their password in the login window.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.sessionPasswordEntryBox.setText("")
#if QT_CONFIG(tooltip)
        self.sessionUserNameEntryBox.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>This specifies the username used for RDP connection authentication.</p><p>When set to <span style=\" font-weight:600;\">ask</span>, the user who is attempting to log in needs to enter their username in the login window.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.sessionUserNameEntryBox.setText("")
        self.label_4.setText(QCoreApplication.translate("sessionConfigForm", u"User Name", None))
        self.label_5.setText(QCoreApplication.translate("sessionConfigForm", u"Session Name", None))
#if QT_CONFIG(tooltip)
        self.sessionNameBox.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>You can rename the session here. The configuration will automatically be updated.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.sessionNameBox.setText("")
#if QT_CONFIG(tooltip)
        self.chansrvport_label.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>If you see this then XRDP is in DEBUG mode.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.chansrvport_label.setText(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p><span style=\" font-weight:600;\">chansrvport</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.chansrvPortEntryBox.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>If you can see this then DEBUG mode is configured and this option has been automatically added to the .ini file. It will be removed if DEBUG mode is deactivated.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.chansrvPortEntryBox.setText("")
        self.label_13.setText(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Channel Overrides</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.useXrdpVrCheckBox.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.useXrdpVrCheckBox.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.useXrdpVrCheckBox.setText(QCoreApplication.translate("sessionConfigForm", u"Enable XRDP Video Streaming Channel (xrdpvr)", None))
#if QT_CONFIG(tooltip)
        self.useClipRdrCheckBox.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.useClipRdrCheckBox.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.useClipRdrCheckBox.setText(QCoreApplication.translate("sessionConfigForm", u"Enable Clipboard Re-direction Channel (cliprdr)", None))
#if QT_CONFIG(tooltip)
        self.useRAILCheckBox.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.useRAILCheckBox.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.useRAILCheckBox.setText(QCoreApplication.translate("sessionConfigForm", u"Enable Remote Applications Integrated Locally channel (RAIL)", None))
#if QT_CONFIG(tooltip)
        self.useRdpSndCheckBox.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.useRdpSndCheckBox.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.useRdpSndCheckBox.setText(QCoreApplication.translate("sessionConfigForm", u"Enable Sound Re-direction Channel (rdpsnd)", None))
#if QT_CONFIG(tooltip)
        self.useDrDynVcCheckBox.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.useDrDynVcCheckBox.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.useDrDynVcCheckBox.setText(QCoreApplication.translate("sessionConfigForm", u"Enable initiation of Additional Dynamic Virtual Channels (drdynvc)", None))
        self.useRdpDrCheckBox.setText(QCoreApplication.translate("sessionConfigForm", u"Enable Device Re-direction Channel (rdpdr)", None))
#if QT_CONFIG(tooltip)
        self.enableOverridesCheckBox.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>Enable this if you wish to override the global channels settings for this particular connection.</p><p>XRDPConfigurator will automatically add these settings into your resultant INI file.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.enableOverridesCheckBox.setText(QCoreApplication.translate("sessionConfigForm", u"Enable Channel Overrides ", None))
#if QT_CONFIG(tooltip)
        self.sessionSectionName.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>This is the section name within the INI configuration file. If you delete or add a session, all session sections will automatically be renumbered.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.sessionSectionName.setText("")
#if QT_CONFIG(tooltip)
        self.debugXRDPCheckbox.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p><span style=\" color:#ff0000;\">This is a special DEBUG option. When checked, two lines are entered in the [xrdp1] section to enable debugging of Xrdp.</span></p><p><span style=\" color:#ff0000;\">This option is normally used by developers.</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.debugXRDPCheckbox.setText(QCoreApplication.translate("sessionConfigForm", u"XRDP DEBUG", None))
        self.serverbpplabel.setText(QCoreApplication.translate("sessionConfigForm", u"Server bpp", None))
        self.serverbppcombobox.setItemText(0, "")
        self.serverbppcombobox.setItemText(1, QCoreApplication.translate("sessionConfigForm", u"15", None))
        self.serverbppcombobox.setItemText(2, QCoreApplication.translate("sessionConfigForm", u"16", None))
        self.serverbppcombobox.setItemText(3, QCoreApplication.translate("sessionConfigForm", u"24", None))
        self.serverbppcombobox.setItemText(4, QCoreApplication.translate("sessionConfigForm", u"32", None))

#if QT_CONFIG(tooltip)
        self.serverbppcombobox.setToolTip(QCoreApplication.translate("sessionConfigForm", u"<html><head/><body><p>Secify a colour depth for this session.</p><p>e.g. 15, 16, 24, or 32 bits per pixel.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

